version: '3.8'
services:
  currencyexchange:
    image: 'currencyexchange:latest'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - "EXCHANGE_API_API_KEY=${EXCHANGE_API_API_KEY}"
    volumes:
      - ./logs:/app/logs
